#!/usr/bin/env bash

# This script is used to transfer files from local to remote server
# Usage: ./transfer_file.sh <local_file> <remote_server> <remote_path>

if [ $# -lt 4 ]; then
    echo "Usage: ./transfer_file.sh <local_file> <remote_server> <remote_path> <remote_user>" >&2
    exit 1
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"

echo "File transfer complete."
