#!/usr/bin/env bash

# This script is used to install and start  a nginx web server
apt -y update
apt -y install nginx

# Start nginx web server
echo "Package installation complete"
ufw allow 'Nginx HTTP'
echo "Hello, World!" > /var/www/html/index.html
service nginx start
