#!/usr/bin/env bash
# Install and configures nginx server

sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.html

sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

sudo /etc/init.d/nginx start


if ! pgrep nginx > /dev/null
then
    /etc/init.d/nginx start

fi
