#!/usr/bin/env bash

# This script is used to install and start  a nginx web server

sudo apt -y update
sudo apt -y install nginx &

install_pid=$!
wait $install_pid

# Start nginx web server
echo "Package installation complete"
ufw allow 'Nginx HTTP'
sudo echo "Hello, World!" > /var/www/html/index.html
sudo service nginx start
