#!/usr/bin/env bash
# Configures Nginx to include a custom HTTP header
# The header will be X-Served-By with the value of the server's hostname

# Update packages and install Nginx
apt-get update
apt-get install -y nginx

# Get the hostname of the server
HOSTNAME=$(hostname)

# Configure Nginx
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By $HOSTNAME;
    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart

# Ensure Nginx starts on boot
systemctl enable nginx

# Create a simple HTML file
echo "Hello World!" > /var/www/html/index.html

# Set appropriate permissions
chown -R www-data:www-data /var/www/html
chmod -R 755 /var/www
